/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthLayoutRouteImport } from './routes/_authLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as WebhookIncomingRouteImport } from './routes/webhook/incoming'
import { Route as AuthLayoutAuthRegisterRouteImport } from './routes/_authLayout/auth/register'
import { Route as AuthLayoutAuthLoginRouteImport } from './routes/_authLayout/auth/login'

const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhookIncomingRoute = WebhookIncomingRouteImport.update({
  id: '/webhook/incoming',
  path: '/webhook/incoming',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutAuthRegisterRoute = AuthLayoutAuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutAuthLoginRoute = AuthLayoutAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/webhook/incoming': typeof WebhookIncomingRoute
  '/dashboard': typeof DashboardIndexRoute
  '/auth/login': typeof AuthLayoutAuthLoginRoute
  '/auth/register': typeof AuthLayoutAuthRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/webhook/incoming': typeof WebhookIncomingRoute
  '/dashboard': typeof DashboardIndexRoute
  '/auth/login': typeof AuthLayoutAuthLoginRoute
  '/auth/register': typeof AuthLayoutAuthRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authLayout': typeof AuthLayoutRouteWithChildren
  '/webhook/incoming': typeof WebhookIncomingRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_authLayout/auth/login': typeof AuthLayoutAuthLoginRoute
  '/_authLayout/auth/register': typeof AuthLayoutAuthRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/webhook/incoming'
    | '/dashboard'
    | '/auth/login'
    | '/auth/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/webhook/incoming'
    | '/dashboard'
    | '/auth/login'
    | '/auth/register'
  id:
    | '__root__'
    | '/'
    | '/_authLayout'
    | '/webhook/incoming'
    | '/dashboard/'
    | '/_authLayout/auth/login'
    | '/_authLayout/auth/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  WebhookIncomingRoute: typeof WebhookIncomingRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhook/incoming': {
      id: '/webhook/incoming'
      path: '/webhook/incoming'
      fullPath: '/webhook/incoming'
      preLoaderRoute: typeof WebhookIncomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout/auth/register': {
      id: '/_authLayout/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthLayoutAuthRegisterRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_authLayout/auth/login': {
      id: '/_authLayout/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLayoutAuthLoginRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
  }
}

interface AuthLayoutRouteChildren {
  AuthLayoutAuthLoginRoute: typeof AuthLayoutAuthLoginRoute
  AuthLayoutAuthRegisterRoute: typeof AuthLayoutAuthRegisterRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutAuthLoginRoute: AuthLayoutAuthLoginRoute,
  AuthLayoutAuthRegisterRoute: AuthLayoutAuthRegisterRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  WebhookIncomingRoute: WebhookIncomingRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
